echo register_write fch_reg 0 0 | simple_switch_CLI
echo register_write fch_reg 1 64 | simple_switch_CLI
echo register_write fch_reg 2 16 | simple_switch_CLI
echo register_write fch_reg 3 36 | simple_switch_CLI
echo register_write fch_reg 4 4 | simple_switch_CLI
echo register_write fch_reg 5 38 | simple_switch_CLI
echo register_write fch_reg 6 23 | simple_switch_CLI

echo register_write g_reg 0 1 | simple_switch_CLI
echo register_write g_reg 1 41 | simple_switch_CLI
echo register_write g_reg 2 54 | simple_switch_CLI
echo register_write g_reg 3 40 | simple_switch_CLI
echo register_write g_reg 4 12 | simple_switch_CLI
echo register_write g_reg 5 59 | simple_switch_CLI
echo register_write g_reg 6 59 | simple_switch_CLI
echo register_write g_reg 7 1 | simple_switch_CLI
echo register_write g_reg 8 57 | simple_switch_CLI
echo register_write g_reg 9 42 | simple_switch_CLI
echo register_write g_reg 10 35 | simple_switch_CLI
echo register_write g_reg 11 2 | simple_switch_CLI
echo register_write g_reg 12 39 | simple_switch_CLI
echo register_write g_reg 13 44 | simple_switch_CLI
echo register_write g_reg 14 25 | simple_switch_CLI
echo register_write g_reg 15 48 | simple_switch_CLI
